spring.application.name=library_project
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.jpa.properties.hibernate.default_schema=library
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}